modLoader="javafml"
loaderVersion="[31,)" #forge version dep
issueTrackerURL="https://github.com/iChun/Globe/issues"

[[mods]]
    modId="globe"
    version="${file.jarVersion}" #mandatory
    displayName="Globe"
    displayURL="http://ichun.me/mods/globe/"
    authors="iChun"
    description='''
    Globe - verb - form (something) into a globe
    '''

[[dependencies.globe]]
    modId="ichunutil"
    mandatory=true
    versionRange="[8.0.0,9)"
    ordering="NONE"
    side="BOTH"
